# https://docs.github.com/en/actions

name: "Renew"

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "1 0 1 1 *"

jobs:
  license:
    name: "License"

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        php-version:
          - "8.2"

        dependencies:
          - "locked"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac" # v4
        with:
          token: "${{ secrets.LCTRS_BOT_TOKEN }}"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@2.25.5"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Set up problem matchers for PHP"
        run: "echo \"::add-matcher::${{ runner.tool_cache }}/php.json\""

      - name: "Install ${{ matrix.dependencies }} dependencies with composer"
        uses: "ramsey/composer-install@2.2.0"
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: "Run update license script"
        run: "php update-license.php"

      - name: "Commit modified files"
        uses: "stefanzweifel/git-auto-commit-action@v4.16.0"
        with:
          commit_author: "lctrs-bot <bot@prmntr.me>"
          commit_message: "license: update year"
          commit_user_email: "bot@prmntr.me"
          commit_user_name: "lctrs-bot"
