# https://docs.github.com/en/actions

name: "Renew"

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "1 0 1 1 *"

env:
  PHP_EXTENSIONS: "mbstring"

jobs:
  license:
    name: "License"

    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "7.4"

        dependencies:
          - "locked"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.3.4"
        with:
          token: "${{ secrets.LCTRS_BOT_TOKEN }}"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@2.10.0"
        with:
          coverage: "none"
          extensions: "${{ env.PHP_EXTENSIONS }}"
          php-version: "${{ matrix.php-version }}"

      - name: "Determine composer cache directory"
        uses: "./.github/actions/composer/composer/determine-cache-directory"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2.1.4"
        with:
          path: "${{ env.COMPOSER_CACHE_DIR }}"
          key: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-${{ matrix.dependencies }}-"

      - name: "Install ${{ matrix.dependencies }} dependencies with composer"
        uses: "./.github/actions/composer/composer/install"
        with:
          dependencies: "${{ matrix.dependencies }}"

      - name: "Run update license script"
        run: "php update-license.php"

      - name: "Commit modified files"
        uses: "stefanzweifel/git-auto-commit-action@v4.9.1"
        with:
          commit_author: "lctrs-bot <bot@prmntr.me>"
          commit_message: "license: update year"
          commit_user_email: "bot@prmntr.me"
          commit_user_name: "lctrs-bot"
